# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

forward_cpp_flies <- function(allprobs, delta, Gamma1, Gamma2, startDD, tod) {
    .Call(`_Lcpp_forward_cpp_flies`, allprobs, delta, Gamma1, Gamma2, startDD, tod)
}

forward_cpp_g <- function(allprobs, delta, Gamma) {
    .Call(`_Lcpp_forward_cpp_g`, allprobs, delta, Gamma)
}

forward_cpp_h <- function(allprobs, delta, Gamma) {
    .Call(`_Lcpp_forward_cpp_h`, allprobs, delta, Gamma)
}

forward_cpp_p <- function(allprobs, delta, Gamma, tod) {
    .Call(`_Lcpp_forward_cpp_p`, allprobs, delta, Gamma, tod)
}

rep_times_cpp <- function(x, times) {
    .Call(`_Lcpp_rep_times_cpp`, x, times)
}

semigroup_cpp <- function(Q, times) {
    .Call(`_Lcpp_semigroup_cpp`, Q, times)
}

