# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

forward_cpp_h <- function(allprobs, delta, Gamma) {
    .Call(`_Lcpp_forward_cpp_h`, allprobs, delta, Gamma)
}

forward_cpp_g <- function(allprobs, delta, Gamma) {
    .Call(`_Lcpp_forward_cpp_g`, allprobs, delta, Gamma)
}

forward_cpp_p <- function(allprobs, delta, Gamma, tod) {
    .Call(`_Lcpp_forward_cpp_p`, allprobs, delta, Gamma, tod)
}

forward_cpp_s <- function(allprobs, delta, Gamma, agsizes) {
    .Call(`_Lcpp_forward_cpp_s`, allprobs, delta, Gamma, agsizes)
}

forward_cpp_sp <- function(allprobs, delta, Gamma, agsizes, tod) {
    .Call(`_Lcpp_forward_cpp_sp`, allprobs, delta, Gamma, agsizes, tod)
}

logalpha_cpp <- function(allprobs, delta, Gamma) {
    .Call(`_Lcpp_logalpha_cpp`, allprobs, delta, Gamma)
}

logbeta_cpp <- function(allprobs, Gamma) {
    .Call(`_Lcpp_logbeta_cpp`, allprobs, Gamma)
}

viterbi_g_cpp <- function(allprobs, delta, Gamma) {
    .Call(`_Lcpp_viterbi_g_cpp`, allprobs, delta, Gamma)
}

forward_cpp_flies <- function(allprobs, delta, Gamma1, Gamma2, startDD, tod) {
    .Call(`_Lcpp_forward_cpp_flies`, allprobs, delta, Gamma1, Gamma2, startDD, tod)
}

rep_times <- function(x, times) {
    .Call(`_Lcpp_rep_times`, x, times)
}

tpm_g_cpp <- function(Z, beta, N, byrow) {
    .Call(`_Lcpp_tpm_g_cpp`, Z, beta, N, byrow)
}

semigroup_cpp <- function(Q, times) {
    .Call(`_Lcpp_semigroup_cpp`, Q, times)
}

tpm_thinned_t_cpp <- function(Gamma, t) {
    .Call(`_Lcpp_tpm_thinned_t_cpp`, Gamma, t)
}

